### ISSUE TITLE
Training on different dataset/language leads to a lot of [UNK] tokens in the result

### ISSUE THREAD

**Issue by benSchaper** [nlpyang/PreSumm#184]
We trained with the bert-base-german-cased model and the following parameters: 
`python train.py  -task abs -mode train -bert_data_path BERT_DATA_PATH -dec_dropout 0.2  -model_path MODEL_PATH -sep_optim true -lr_bert 0.002 -lr_dec 0.2 -save_checkpoint_steps 200 -batch_size 140 -train_steps 8000 -report_every 20 -accum_count 10 -use_bert_emb true -use_interval true -warmup_steps_bert 20000 -warmup_steps_dec 10000 -max_pos 512 -visible_gpus -1  -log_file ../logs/abs_bert_cnndm`

This is an example for a candidate file after about 1200 training steps and ca. 40000 training examples:

`die [UNK] hat die [UNK] in den vergangenen jahren in den usa .<q>nun hat das neue neue neue [UNK] für die [UNK] für den vergangenen jahre des [UNK] . [UNK] will das ändern . [UNK] ist das ändern ? [UNK] ' [UNK] ' . [UNK] der [UNK] ' ' [UNK] .<q>das ist es gibt es es geht es . [UNK] [UNK] ' ist einblick . [UNK] ? [UNK] und die [UNK] [UNK] . ' [UNK] der neuen [UNK] . . [UNK] . [UNK] [SEP] [CLS] [UNK] [UNK] [UNK] [SEP] [unused3001] [CLS] [UNK] [SEP] [SEP] [CLS] [SEP] [CLS]  [CLS] [UNK]  [CLS] [SEP] [unused3001] [unused3001] [CLS] [SEP] [SEP] [unused3001] [SEP] [CLS] [unused3001] [CLS]  [unused3001] [CLS] [unused3001] [unused3001] [unused3001] [SEP] [unused3001] [UNK] [CLS] [UNK] [unused3001] [CLS] [CLS] [CLS] [UNK] [CLS] [CLS] [SEP] [UNK] [CLS] [SEP]  [CLS]  [SEP] [CLS] [CLS] [CLS]`

Is this how it's supposed to look after this amount of training or do we have to change something?
Thank you in advance!

**Comment by SebastianVeile** [comment]
This might be because the -use_bert_basic_tokenizer is set to false. I am not actually sure why they don't use it for their preprocessing. But multilingual Bert removes accents from words, so words with characters like ö are not in the vocab. This means if you do not use the -use_bert_basic_tokenizer you will still have words in the source document with accents, which then can't be looked up in the vocab file and will turn into an unk token. 

You can read more about it here under the Tokenization headline - https://github.com/google-research/bert/blob/master/multilingual.md

My fix for danish was to set -use_bert_basic_tokenizer to true at preprocessing step 4 or 5. Then all "å" characters were preprocessed to "a"

**Comment by SebastianVeile** [comment]
You have a lot of unk tokens. These only appear when you have a word in the src text that is not in the vocab file or that cant be built from the subtokens. You might what to look into what words might be and see if you can make any changes.

Also, I trained on around 45000 documents for 50000 steps. After evaluating, the best model was at step 20.000. So you might what to extend your training. It was not perfect summaries nor sentences, but it was okay. I believe more data is needed to gain great results.

**Comment by benSchaper** [comment]
Thank you for your insights. I changed use-bert-tokenizer to true now and that seems to fix the issue! I'm definitely going to train for more iterations and on gpus, so I hope for better results and less unk tokens.
